/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddApplication: typeof import('./components/dashboard/Modal/AddApplication.vue')['default']
    ApplicationAllowOrigins: typeof import('./components/dashboard/ApplicationAllowOrigins.vue')['default']
    ApplicationItem: typeof import('./components/dashboard/ApplicationItem.vue')['default']
    ApplicationRules: typeof import('./components/dashboard/ApplicationRules.vue')['default']
    ApplicationStatus: typeof import('./components/dashboard/ApplicationStatus.vue')['default']
    ApplicationType: typeof import('./components/dashboard/ApplicationType.vue')['default']
    ConnectButton: typeof import('./components/ConnectButton.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    NoData: typeof import('./components/NoData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleCDBar: typeof import('./components/dashboard/RuleCDBar.vue')['default']
    SecretDisplay: typeof import('./components/dashboard/SecretDisplay.vue')['default']
    SideBar: typeof import('./components/dashboard/SideBar.vue')['default']
    WalletDialog: typeof import('./components/WalletDialog.vue')['default']
  }
}
